source 'https://rubygems.org'

gem 'middleman', '~> 4.2.1'
gem 'middleman-autoprefixer', '~> 2.7'
gem 'tzinfo-data', platforms: [:mswin, :mingw, :jruby]
gem "middleman-sprockets", '~> 4.1.0'
gem 'sprockets'
gem 'wdm', '~> 0.1', platforms: [:mswin, :mingw]
gem 'sass', '~> 3.4.25'
gem 'betterlorem'